version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-pedidos
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pedidos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pedidos-network

volumes:
  postgres_data:

networks:
  pedidos-network:
    driver: bridge
